from typing import Protocol
from uuid import UUID

from .entities import Membership, RefreshToken, Role, User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...

    async def get_by_email(self, email: str) -> User | None: ...

    async def list_all(self, limit: int = 100, offset: int = 0) -> list[User]: ...

    async def count(self) -> int: ...

    async def add(self, user: User) -> None: ...

    async def update(self, user: User) -> None: ...


class RoleRepository(Protocol):
    async def get_by_id(self, role_id: UUID) -> Role | None: ...

    async def get_by_name(self, name: str) -> Role | None: ...

    async def list_all(self) -> list[Role]: ...

    async def add(self, role: Role) -> None: ...


class MembershipRepository(Protocol):
    async def get_by_id(self, membership_id: UUID) -> Membership | None: ...

    async def get_for_user_in_organization(
        self, user_id: UUID, organization_id: UUID
    ) -> Membership | None: ...

    async def list_for_user(self, user_id: UUID) -> list[Membership]: ...

    async def list_for_organization(self, organization_id: UUID) -> list[Membership]: ...

    async def add(self, membership: Membership) -> None: ...

    async def remove(self, membership_id: UUID) -> None: ...


class RefreshTokenRepository(Protocol):
    async def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...

    async def add(self, token: RefreshToken) -> None: ...

    async def update(self, token: RefreshToken) -> None: ...

    async def revoke_all_for_user(self, user_id: UUID) -> None: ...
