from typing import Protocol
from uuid import UUID

from .entities import Organization


class OrganizationRepository(Protocol):
    async def get_by_id(self, organization_id: UUID) -> Organization | None: ...

    async def get_by_slug(self, slug: str) -> Organization | None: ...

    async def get_root(self) -> Organization | None: ...

    async def list_all(self) -> list[Organization]: ...

    async def list_children(self, parent_id: UUID) -> list[Organization]: ...

    async def add(self, organization: Organization) -> None: ...

    async def update(self, organization: Organization) -> None: ...
